---
- name: Install Apache web server
  hosts: all
  become: yes
  tasks:
    
    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present
     
    - name: Ensure Apache is running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
     
